### ISSUE TITLE
Zombie sessions on connection after sending transactions [Artemis 2.12.0]

### ISSUE THREAD

**Issue by tmota900** [go-stomp/stomp#110]
Greetings, I'm sending transactions, this is generating a new frame for each transaction, this in Artemis is creating a new session for that connection, after alot of transactions, this "not closed sessions" makes the Artemis server to crash, making it come alive only after restart. In an attempt to close this sessions i've created a connection pool with a TTL for each connection, this closes the connection gracefully but it also lefts the sessions in the Artemis server, making it to go down after a while too. Is there any way to prevent this behavior?  

how the transaction is being handle:

``` golang
func processTransaction(t Transaction, workerId int) error {
	tx, err := (*connectionPool.GetConnection(workerId)).BeginWithError()
	if err != nil {
		return err
	}
	for _, message := range t.MsgArr {
		err := tx.Send(activemq.GetAmqConfig().Queue, "text/plain", []byte(message), stomp.SendOpt.Header("persistent", "true"))
		if err != nil {
			return err
		}
	}
	return tx.Commit()

}
```

docker-compose.yml
``` yaml
version: "3.1"
services:
    activemq_artemis:
        image: vromero/activemq-artemis:2.12.0
        restart: always
        container_name: activemq_artemis
        environment:
            ARTEMIS_USERNAME: admin
            ARTEMIS_PASSWORD: admin
            ARTEMIS_MIN_MEMORY: 1512M
            ARTEMIS_MAX_MEMORY: 3048M
        volumes:
            - ./data/activemq_artemis:/var/lib/artemis-instance
        ports:
            - 61616:61616
            - 61613:61613
            - 8161:8161 #webconsole

```
